# Generated by Django 4.2.2 on 2023-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='EMPTY', max_length=50, verbose_name='CREATOR'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='CONTENT'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=50, verbose_name='TITLE'),
        ),
    ]
